server:
  port: 8040
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8090/eureka/

spring:
  application:
    name: "Api-Gateway"
  cloud:
    gateway:
      routes:
        - id: Transaction
          uri: http://transactionapi:8081/
          predicates:
            - Path=/transaction/**
          filters:c
            - StripPrefix=1
        - id: Personal
          uri: http://personalapi:8082/
          predicates:
            - Path=/personal/**
          filters:
            - StripPrefix=1
        - id: Enterprise
          uri: http://enterpriseapi:8083/
          predicates:
            - Path=/enterprise/**
          filters:
            - StripPrefix=1
        - id: Product
          uri: http://productapi:8084/
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: Card
          uri: http://cardsapi:8085/
          predicates:
            - Path=/card/**
          filters:
            - StripPrefix=1
        - id: Yanki
          uri: http://yankiapi:8086/
          predicates:
              - Path=/yanki/**
          filters:
              - StripPrefix=1